name: 'Verify Copyright File'
description: 'Verifies that the copyright file exists and validates its format for App Store metadata'
runs:
  using: 'composite'
  steps:
    - name: Validate copyright metadata
      shell: bash
      working-directory: ios/App
      run: |
        echo "📋 Checking copyright file..."
        COPYRIGHT_FILE="fastlane/metadata/en-US/copyright.txt"
        
        # Check if file exists
        if [ ! -f "$COPYRIGHT_FILE" ]; then
          echo "❌ Copyright file not found at: $COPYRIGHT_FILE"
          exit 1
        fi
        
        echo "✅ Copyright file exists at: $COPYRIGHT_FILE"
        
        # Read and validate copyright content
        # Note: tr removes newlines/returns, xargs normalizes whitespace (collapses multiple spaces)
        COPYRIGHT_CONTENT=$(tr -d '\n\r' < "$COPYRIGHT_FILE" | xargs)
        echo "📝 Copyright value: $COPYRIGHT_CONTENT"
        
        # Validate that content is not empty
        if [ -z "$COPYRIGHT_CONTENT" ]; then
          echo "❌ Copyright file is empty"
          exit 1
        fi
        
        # Source shared validation logic
        source "$GITHUB_WORKSPACE/scripts/lib/validate-copyright.sh"
        
        # Validate copyright format
        validate_copyright_content "$COPYRIGHT_CONTENT"
        
        if [ "$VALIDATION_PASSED" = "false" ]; then
          echo "❌ Copyright format invalid: $ERROR_MSG"
          echo "   Expected formats:"
          echo "     - © YYYY Company Name (recommended)"
          echo "     - © Company Name (year added automatically)"
          echo "     - YYYY Company Name (© added automatically)"
          echo "     - Company Name (both © and year added automatically)"
          echo "   Note: Company names must be at least 2 characters and contain at least one letter"
          echo "   Found: $COPYRIGHT_CONTENT"
          exit 1
        fi
        
        # Parse copyright to validate format
        # The Fastlane script expects formats like:
        # - "© YYYY Company Name" (recommended)
        # - "YYYY Company Name" (legacy)
        # - "© Company Name" (no year)
        # - "Company Name" (fallback)
        
        # Split content into words for parsing
        read -ra WORDS <<< "$COPYRIGHT_CONTENT"
        WORD_COUNT=${#WORDS[@]}
        
        # Extract the first word to check for copyright symbol
        FIRST_WORD="${WORDS[0]}"
        
        # Check if it starts with copyright symbol or is parseable
        if [[ "$FIRST_WORD" == "©" ]]; then
          SECOND_WORD="${WORDS[1]}"
          
          # Check if second word is a year (4 digits)
          if [[ "$SECOND_WORD" =~ ^[0-9]{4}$ ]]; then
            # Format: "© YYYY Company Name"
            COMPANY_NAME="${WORDS[@]:2}"
            echo "✅ Copyright format valid: © $SECOND_WORD $COMPANY_NAME"
          else
            # Format: "© Company Name" (no year)
            COMPANY_NAME="${WORDS[@]:1}"
            echo "✅ Copyright format valid: © $COMPANY_NAME (year will be added automatically)"
          fi
        elif [[ "$FIRST_WORD" =~ ^[0-9]{4}$ ]]; then
          # Format: "YYYY Company Name" (legacy, no © symbol)
          COMPANY_NAME="${WORDS[@]:1}"
          echo "✅ Copyright format valid: $FIRST_WORD $COMPANY_NAME (© symbol will be added automatically)"
        else
          # Format: "Company Name" (no © symbol, no year)
          COMPANY_NAME="$COPYRIGHT_CONTENT"
          echo "✅ Copyright format valid: $COMPANY_NAME (© symbol and year will be added automatically)"
        fi
        
        echo "✅ Copyright metadata validation passed"
