name: 'Verify Copyright File'
description: 'Verifies that the copyright file exists and logs its contents for debugging'
runs:
  using: 'composite'
  steps:
    - name: Log copyright value
      shell: bash
      working-directory: ios/App
      run: |
        echo "📋 Checking copyright file..."
        COPYRIGHT_FILE="fastlane/metadata/en-US/copyright.txt"
        if [ -f "$COPYRIGHT_FILE" ]; then
          echo "✅ Copyright file exists at: $COPYRIGHT_FILE"
          echo "📝 Copyright value:"
          cat "$COPYRIGHT_FILE"
        else
          echo "❌ Copyright file not found at: $COPYRIGHT_FILE"
          exit 1
        fi
